version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demopass
      - POSTGRES_DB=resqdb
    ports:
      - "5433:5433"